controller:
  config:
    # Disable strict path validation, to work around a bug in ingress-nginx
    # https://github.com/kubernetes/ingress-nginx/issues/11176
    strict-validate-path-type: false

  service:
    annotations:
      service:
        beta:
          kubernetes:
            io/azure-load-balancer-internal: true
    externalTrafficPolicy: Local
  metrics:
    enabled: true
    service:
      annotations: 
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"


rbac:
  create: true